package com.redhat.demo.traffic_violations;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Driver implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label(value = "Age")
	private java.lang.Integer age;
	@org.kie.api.definition.type.Label(value = "State")
	private java.lang.String state;
	@org.kie.api.definition.type.Label(value = "City")
	private java.lang.String city;
	@org.kie.api.definition.type.Label(value = "Violations")
	private java.util.List<com.redhat.demo.traffic_violations.Violation> violations;
	@org.kie.api.definition.type.Label(value = "Fine Amount")
	private java.lang.Double fineAmount;
	@org.kie.api.definition.type.Label(value = "Total Points")
	private java.lang.Integer totalPoints;
	@org.kie.api.definition.type.Label(value = "Reason")
	private java.lang.String reason;

	public Driver() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public java.lang.String getState() {
		return this.state;
	}

	public void setState(java.lang.String state) {
		this.state = state;
	}

	public java.lang.String getCity() {
		return this.city;
	}

	public void setCity(java.lang.String city) {
		this.city = city;
	}

	public java.util.List<com.redhat.demo.driver_dept_traffic_violations.Violation> getViolations() {
		return this.violations;
	}

	public void setViolations(
			java.util.List<com.redhat.demo.driver_dept_traffic_violations.Violation> violations) {
		this.violations = violations;
	}

	public java.lang.Double getFineAmount() {
		return this.fineAmount;
	}

	public void setFineAmount(java.lang.Double fineAmount) {
		this.fineAmount = fineAmount;
	}

	public java.lang.Integer getTotalPoints() {
		return this.totalPoints;
	}

	public void setTotalPoints(java.lang.Integer totalPoints) {
		this.totalPoints = totalPoints;
	}

	public java.lang.String getReason() {
		return this.reason;
	}

	public void setReason(java.lang.String reason) {
		this.reason = reason;
	}

	public Driver(
			java.lang.String name,
			java.lang.Integer age,
			java.lang.String state,
			java.lang.String city,
			java.util.List<com.redhat.demo.driver_dept_traffic_violations.Violation> violations,
			java.lang.Double fineAmount, java.lang.Integer totalPoints,
			java.lang.String reason) {
		this.name = name;
		this.age = age;
		this.state = state;
		this.city = city;
		this.violations = violations;
		this.fineAmount = fineAmount;
		this.totalPoints = totalPoints;
		this.reason = reason;
	}

}
