package com.redhat.demo.traffic_violations;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Violation implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Code")
	private java.lang.String code;
	@org.kie.api.definition.type.Label(value = "Points")
	private java.lang.Integer points;
	@org.kie.api.definition.type.Label(value = "Violation Date")
	private java.util.Date violationDate;
	@org.kie.api.definition.type.Label(value = "Type")
	private java.lang.String type;
	@org.kie.api.definition.type.Label(value = "Fine Amount")
	private java.lang.Float fineAmount;
	@org.kie.api.definition.type.Label(value = "Speed Limit")
	private java.lang.Integer speedLimit;
	@org.kie.api.definition.type.Label(value = "Actual Speed")
	private java.lang.Integer actualSpeed;

	public Violation() {
	}

	public java.lang.String getCode() {
		return this.code;
	}

	public void setCode(java.lang.String code) {
		this.code = code;
	}

	public java.lang.Integer getPoints() {
		return this.points;
	}

	public void setPoints(java.lang.Integer points) {
		this.points = points;
	}

	public java.util.Date getViolationDate() {
		return this.violationDate;
	}

	public void setViolationDate(java.util.Date violationDate) {
		this.violationDate = violationDate;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.Float getFineAmount() {
		return this.fineAmount;
	}

	public void setFineAmount(java.lang.Float fineAmount) {
		this.fineAmount = fineAmount;
	}

	public java.lang.Integer getSpeedLimit() {
		return this.speedLimit;
	}

	public void setSpeedLimit(java.lang.Integer speedLimit) {
		this.speedLimit = speedLimit;
	}

	public java.lang.Integer getActualSpeed() {
		return this.actualSpeed;
	}

	public void setActualSpeed(java.lang.Integer actualSpeed) {
		this.actualSpeed = actualSpeed;
	}

	public Violation(java.lang.String code, java.lang.Integer points,
			java.util.Date violationDate, java.lang.String type,
			java.lang.Float fineAmount, java.lang.Integer speedLimit,
			java.lang.Integer actualSpeed) {
		this.code = code;
		this.points = points;
		this.violationDate = violationDate;
		this.type = type;
		this.fineAmount = fineAmount;
		this.speedLimit = speedLimit;
		this.actualSpeed = actualSpeed;
	}

}
